"""Французский глоссарий RimWorld-терминов (EN -> FR).

Как и src/glossary_terms_de.py — сгенерировано как лучшее приближение,
без сверки с носителем языка или официальной французской локализацией
RimWorld. Если у кого-то есть доступ к официальному переводу — стоит
сверить и поправить."""
from __future__ import annotations

GLOSSARY_FR: dict[str, str] = {
    "hediffs": "affections",
    "hediff": "affection",
    "xenotypes": "xénotypes",
    "xenotype": "xénotype",
    "xenogerms": "xénogermes",
    "xenogerm": "xénogerme",
    "xenogenes": "xénogènes",
    "xenogene": "xénogène",
    "genes": "gènes",
    "gene": "gène",
    "archite": "archite",
    "archotech": "archotech",
    "psycasters": "psilanceurs",
    "psycaster": "psilanceur",
    "psycasts": "psipouvoirs",
    "psycast": "psipouvoir",
    "psylink": "psilien",
    "psyfocus": "psifocus",
    "psychic sensitivity": "sensibilité psychique",
    "resonance": "résonance",
    "enlightenment": "illumination",
    "mechanoids": "mécanoïdes",
    "mechanoid": "mécanoïde",
    "ideoligion": "idéologie",
    "ideology": "idéologie",
    "precepts": "préceptes",
    "precept": "précepte",
    "colonists": "colons",
    "colonist": "colon",
    "pawns": "personnages",
    "pawn": "personnage",
    "raiders": "assaillants",
    "raid": "raid",
    "traits": "traits",
    "trait": "trait",
    "passions": "passions",
    "passion": "passion",
    "backstory": "passé",
    "factions": "factions",
    "faction": "faction",
    "quests": "quêtes",
    "quest": "quête",
    "caravans": "caravanes",
    "caravan": "caravane",
    "apparel": "vêtements",
    "mood": "humeur",
    "needs": "besoins",
    "need": "besoin",
    "capacities": "capacités corporelles",
    "capacity": "capacité corporelle",
    "aptitudes": "aptitudes",
    "aptitude": "aptitude",
    "stat modifiers": "modificateurs de statistiques",
    "mental break": "effondrement mental",
    "prison break": "évasion de prison",
    "tolerance": "tolérance",
    "overdose": "overdose",
    "immunity": "immunité",
    "abilities": "capacités",
    "ability": "capacité",
    "research": "recherche",
    "rituals": "rituels",
    "ritual": "rituel",
    "meditation": "méditation",
    "storyteller": "conteur",
    "plasteel": "plastacier",
    "chemfuel": "chimiocarburant",
    "neutroamine": "neutroamine",
    "luciferium": "lucifèrium",
    "pemmican": "pemmican",
    "kibble": "croquettes",
    "thrumbo": "thrumbo",
    "scythers": "faucheurs",
    "scyther": "faucheur",
    "centipedes": "mille-pattes",
    "centipede": "mille-pattes",
    "toxic fallout": "retombées toxiques",
    "solar flare": "éruption solaire",
    "cryptosleep": "cryosommeil",
    "mechanitor": "mécanitor",
    "sanguophages": "sanguophages",
    "sanguophage": "sanguophage",
    "ghouls": "goules",
    "ghoul": "goule",
    "deathrest": "repos mortel",
    "gauranlen tree": "arbre gauranlen",
    "gauranlen": "gauranlen",
    "dryads": "dryades",
    "dryad": "dryade",
    "anima tree": "arbre anima",
    "anima": "anima",
    "ocular warping": "déformation oculaire",
    "turret": "tourelle",
    "mortar": "mortier",
    "server": "serveur",
    "component": "composant",
    "shuttle": "navette",
    "module": "module",
    "habitat": "module d'habitation",
    "crew": "équipage",
    "cargo": "cargaison",
    "reactor": "réacteur",
    "shield": "bouclier",
    "cockpit": "cockpit",
    "hull": "coque",
    "bay": "baie",
    "ammo": "munitions",
    "prisoner": "prisonnier",
    "electrical wiring": "câblage électrique",
    "electrical cable": "câble électrique",
    "heavy-duty": "renforcé",
    "power pole": "poteau électrique",
    "shamblers": "traînards",
    "shambler": "traînard",
    "metalhorrors": "horreurs métalliques",
    "metalhorror": "horreur métallique",
    "fleshbeasts": "bêtes de chair",
    "fleshbeast": "bête de chair",
    "revenants": "revenants",
    "revenant": "revenant",
    "entities": "entités",
    "entity": "entité",
    "bioferrite": "bioferrite",
    "gorehulks": "colosses sanglants",
    "gorehulk": "colosse sanglant",
    "deathpall": "voile mortel",
    "noctol": "noctol",
    "sightstealer": "voleur de regard",
    "sightstealers": "voleurs de regard",
    "toxic gorger": "goinfre toxique",
    "toxic gorgers": "goinfres toxiques",
    "chimera": "chimère",
    "chimeras": "chimères",
    "devourer": "dévoreur",
    "devourers": "dévoreurs",
    "fingerspike": "pointe digitale",
    "fingerspikes": "pointes digitales",
    "obelisk": "obélisque",
    "obelisks": "obélisques",
    "void monolith": "monolithe du vide",
    "monolith": "monolithe",
    "unnatural darkness": "ténèbres contre nature",
    "unnatural corpse": "cadavre contre nature",
    "bloodrain": "pluie de sang",
    "cultist": "adepte",
    "cultists": "adeptes",
    "psychic ritual": "rituel psychique",
    "hold cell": "cellule de détention",
    "pit gate": "portail de la fosse",
    "pit burrow": "terrier de la fosse",
    "flesh whip": "fouet de chair",
    "twisted meat": "chair tordue",
    "corpse withering": "dessèchement du cadavre",
    "ritual mutilation": "mutilation rituelle",
}
