"""Немецкий глоссарий RimWorld-терминов (EN -> DE).

В отличие от src/glossary.py (русский глоссарий), который вырос из
РЕАЛЬНЫХ переводов сообщества, найденных на диске пользователя, для
немецкого такого источника не было — переводы здесь сгенерированы как
лучшее приближение (стандартная немецкая игровая терминология sci-fi/
survival жанра), но НЕ проверены носителем языка или официальной
локализацией. Если у кого-то есть доступ к официальному немецкому
переводу RimWorld — многие термины здесь стоит сверить и поправить."""
from __future__ import annotations

GLOSSARY_DE: dict[str, str] = {
    "hediffs": "Effekte",
    "hediff": "Effekt",
    "xenotypes": "Xenotypen",
    "xenotype": "Xenotyp",
    "xenogerms": "Xenokeime",
    "xenogerm": "Xenokeim",
    "xenogenes": "Xenogene",
    "xenogene": "Xenogen",
    "genes": "Gene",
    "gene": "Gen",
    "archite": "Archit",
    "archotech": "Archotech",
    "psycasters": "Psikaster",
    "psycaster": "Psikaster",
    "psycasts": "Psikräfte",
    "psycast": "Psikraft",
    "psylink": "Psilink",
    "psyfocus": "Psifokus",
    "psychic sensitivity": "psychische Empfindlichkeit",
    "resonance": "Resonanz",
    "enlightenment": "Erleuchtung",
    "mechanoids": "Mechanoiden",
    "mechanoid": "Mechanoid",
    "ideoligion": "Ideologie",
    "ideology": "Ideologie",
    "precepts": "Grundsätze",
    "precept": "Grundsatz",
    "colonists": "Kolonisten",
    "colonist": "Kolonist",
    "pawns": "Figuren",
    "pawn": "Figur",
    "raiders": "Angreifer",
    "raid": "Überfall",
    "traits": "Eigenschaften",
    "trait": "Eigenschaft",
    "passions": "Leidenschaften",
    "passion": "Leidenschaft",
    "backstory": "Hintergrundgeschichte",
    "factions": "Fraktionen",
    "faction": "Fraktion",
    "quests": "Aufträge",
    "quest": "Auftrag",
    "caravans": "Karawanen",
    "caravan": "Karawane",
    "apparel": "Kleidung",
    "mood": "Stimmung",
    "needs": "Bedürfnisse",
    "need": "Bedürfnis",
    "capacities": "körperliche Fähigkeiten",
    "capacity": "körperliche Fähigkeit",
    "aptitudes": "Fertigkeiten",
    "aptitude": "Fertigkeit",
    "stat modifiers": "Statuswertmodifikatoren",
    "mental break": "psychischer Zusammenbruch",
    "prison break": "Gefängnisausbruch",
    "tolerance": "Toleranz",
    "overdose": "Überdosis",
    "immunity": "Immunität",
    "abilities": "Fähigkeiten",
    "ability": "Fähigkeit",
    "research": "Forschung",
    "rituals": "Rituale",
    "ritual": "Ritual",
    "meditation": "Meditation",
    "storyteller": "Erzähler",
    "plasteel": "Plastahl",
    "chemfuel": "Chemtreibstoff",
    "neutroamine": "Neutroamin",
    "luciferium": "Luciferium",
    "pemmican": "Pemmikan",
    "kibble": "Tierfutter",
    "thrumbo": "Thrumbo",
    "scythers": "Schnitter",
    "scyther": "Schnitter",
    "centipedes": "Hundertfüßer",
    "centipede": "Hundertfüßer",
    "toxic fallout": "toxischer Fallout",
    "solar flare": "Sonneneruption",
    "cryptosleep": "Kryoschlaf",
    "mechanitor": "Mechanitor",
    "sanguophages": "Sanguophagen",
    "sanguophage": "Sanguophage",
    "ghouls": "Ghule",
    "ghoul": "Ghul",
    "deathrest": "Todesruhe",
    "gauranlen tree": "Gauranlen-Baum",
    "gauranlen": "Gauranlen",
    "dryads": "Dryaden",
    "dryad": "Dryade",
    "anima tree": "Anima-Baum",
    "anima": "Anima",
    "ocular warping": "Augenverzerrung",
    "turret": "Geschützturm",
    "mortar": "Mörser",
    "server": "Server",
    "component": "Komponente",
    "shuttle": "Shuttle",
    "module": "Modul",
    "habitat": "Wohnmodul",
    "crew": "Besatzung",
    "cargo": "Fracht",
    "reactor": "Reaktor",
    "shield": "Schild",
    "cockpit": "Cockpit",
    "hull": "Rumpf",
    "bay": "Bucht",
    "ammo": "Munition",
    "prisoner": "Gefangener",
    "electrical wiring": "elektrische Verkabelung",
    "electrical cable": "elektrisches Kabel",
    "heavy-duty": "verstärkt",
    "power pole": "Strommast",
    "shamblers": "Schlurfer",
    "shambler": "Schlurfer",
    "metalhorrors": "Metallschrecken",
    "metalhorror": "Metallschrecken",
    "fleshbeasts": "Fleischbestien",
    "fleshbeast": "Fleischbestie",
    "revenants": "Wiedergänger",
    "revenant": "Wiedergänger",
    "entities": "Entitäten",
    "entity": "Entität",
    "bioferrite": "Bioferrit",
    "gorehulks": "Blutkolosse",
    "gorehulk": "Blutkoloss",
    "deathpall": "Todesschleier",
    "noctol": "Noctol",
    "sightstealer": "Blickdieb",
    "sightstealers": "Blickdiebe",
    "toxic gorger": "Giftfresser",
    "toxic gorgers": "Giftfresser",
    "chimera": "Chimäre",
    "chimeras": "Chimären",
    "devourer": "Verschlinger",
    "devourers": "Verschlinger",
    "fingerspike": "Fingerstachel",
    "fingerspikes": "Fingerstacheln",
    "obelisk": "Obelisk",
    "obelisks": "Obelisken",
    "void monolith": "Leere-Monolith",
    "monolith": "Monolith",
    "unnatural darkness": "unnatürliche Dunkelheit",
    "unnatural corpse": "unnatürliche Leiche",
    "bloodrain": "Blutregen",
    "cultist": "Kultist",
    "cultists": "Kultisten",
    "psychic ritual": "psychisches Ritual",
    "hold cell": "Arrestzelle",
    "pit gate": "Grubenportal",
    "pit burrow": "Grubenhöhle",
    "flesh whip": "Fleischpeitsche",
    "twisted meat": "verdrehtes Fleisch",
    "corpse withering": "Leichenverwesung",
    "ritual mutilation": "rituelle Verstümmelung",
}
